<a href="https://colab.research.google.com/github/Sereenamariyam/Data-Analysis/blob/main/space_missions_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import requests
import sqlite3
import pandas as pd

In [40]:
#fetching data from api's
launches_url = "https://api.spacexdata.com/v4/launches"
rockets_url = "https://api.spacexdata.com/v4/rockets"

# Step 1: Load SpaceX Launch Data from API
 ● Use https://api.spacexdata.com/v4/launches
 ● Extract relevant columns: name, date_utc, success, details, rocket
 ● Convert date_utc to datetime and extract the year

In [41]:
#loading launches data
launches = requests.get(launches_url).json()

In [42]:
#Convert to DataFrame
df1 = pd.DataFrame(launches)

#Extract only the needed columns
df1 = df1[['name', 'date_utc', 'success', 'details', 'rocket']]
df1.head()

,name,date_utc,success,details,rocket
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb

In [43]:
# to Convert date_utc and Extract Year
#date_utc is a field (column) in the SpaceX launch API response that represents the date and time
#when a SpaceX rocket launch occurred, in UTC (Coordinated Universal Time) format.
df1['date_utc'] = pd.to_datetime(df1['date_utc'])
df1['year'] = df1['date_utc'].dt.year
df1[['name', 'date_utc', 'year']].head()

          name                  date_utc  year
0    FalconSat 2006-03-24 22:30:00+00:00  2006
1      DemoSat 2007-03-21 01:10:00+00:00  2007
2  Trailblazer 2008-08-03 03:34:00+00:00  2008
3       RatSat 2008-09-28 23:15:00+00:00  2008
4     RazakSat 2009-07-13 03:35:00+00:00  2009

# Step 2: Load Rocket Metadata
● Use  https://api.spacexdata.com/v4/rockets
● Extract id, name, type, active, and stages

In [44]:
#Load Rocket Metadata
rockets = requests.get(rockets_url).json()

In [45]:
#Convert to DataFrame
df2 = pd.DataFrame(rockets)
rockets_df = pd.DataFrame(rockets)[['id', 'name', 'type', 'active', 'stages']]
rockets_df

                         id          name    type  active  stages
0  5e9d0d95eda69955f709d1eb      Falcon 1  rocket   False       2
1  5e9d0d95eda69973a809d1ec      Falcon 9  rocket    True       2
2  5e9d0d95eda69974db09d1ed  Falcon Heavy  rocket    True       2
3  5e9d0d96eda699382d09d1ee      Starship  rocket   False       2

In [46]:
df1

,name,date_utc,success,details,rocket,year
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009
...,...,...,...,...,...,...
200,Transporter-6,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022
201,TTL-1,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022
202,WorldView Legion 1 & 2,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022
203,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022
204,O3b mPower 3.4,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69973a809d1ec,2022

In [47]:
df2

,height,diameter,mass,first_stage,second_stage,engines,landing_legs,payload_weights,flickr_images,name,...,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,wikipedia,description,id
0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...","{'thrust': {'kN': 31, 'lbf': 7000}, 'payloads'...","{'isp': {'sea_level': 267, 'vacuum': 304}, 'th...","{'number': 0, 'material': None}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...","[https://imgur.com/DaCfMsj.jpg, https://imgur....",Falcon 1,...,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...,5e9d0d95eda69955f709d1eb
1,"{'meters': 70, 'feet': 229.6}","{'meters': 3.7, 'feet': 12}","{'kg': 549054, 'lb': 1207920}","{'thrust_sea_level': {'kN': 7607, 'lbf': 17100...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 4, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm1.staticflickr.com/929/2878733830...,Falcon 9,...,2,0,50000000,98,2010-06-04,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_9,Falcon 9 is a two-stage rocket designed and ma...,5e9d0d95eda69973a809d1ec
2,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 12, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm5.staticflickr.com/4599/385838292...,Falcon Heavy,...,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...,5e9d0d95eda69974db09d1ed
3,"{'meters': 118, 'feet': 387}","{'meters': 9, 'feet': 30}","{'kg': 1335000, 'lb': 2943000}","{'thrust_sea_level': {'kN': 128000, 'lbf': 287...","{'thrust': {'kN': 1957, 'lbf': 440000}, 'paylo...","{'isp': {'sea_level': 330, 'vacuum': 380}, 'th...","{'number': 6, 'material': 'stainless steel'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://live.staticflickr.com/65535/489541389...,Starship,...,2,0,7000000,0,2021-12-01,United States,SpaceX,https://en.wikipedia.org/wiki/SpaceX_Starship,Starship and Super Heavy Rocket represent a fu...,5e9d0d96eda699382d09d1ee

In [48]:
# rename the "rocket" columname in df1 and rename "id" columnname in df2 to rocket_id

df1.rename(columns={'rocket': 'rocket_id'}, inplace=True)
df2.rename(columns={'id': 'rocket_id'}, inplace=True)

In [49]:
# prompt: using merge function merge  the two dataframe df1 and df2 using "rocket_id" column
 #full outer join – it includes:

# Rows where rocket_id matches in both DataFrames

# Plus rows that exist only in df1 or only in df2 (unmatched values)

#Use how='inner' → only matches

#Use how='outer' → matches + non-matches from both

#Use how='left' → all rows from left DataFrame (df1) + matches from right

#Use how='right' → all rows from right DataFrame (df2) + matches from left
merged_df = pd.merge(df1, df2, on="rocket_id", how="outer")
merged_df

,name_x,date_utc,success,details,rocket_id,year,height,diameter,mass,first_stage,...,active,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,wikipedia,description
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,ArabSat 6A,2019-04-11 22:35:00+00:00,True,SpaceX will launch Arabsat 6A to a geostationa...,5e9d0d95eda69974db09d1ed,2019.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
202,STP-2,2019-06-25 03:30:00+00:00,True,Space Test Program 2 is a rideshare managed by...,5e9d0d95eda69974db09d1ed,2019.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
203,USSF-44,2022-11-01 13:41:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
204,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
205,NaN,NaT,NaN,NaN,5e9d0d96eda699382d09d1ee,NaN,"{'meters': 118, 'feet': 387}","{'meters': 9, 'feet': 30}","{'kg': 1335000, 'lb': 2943000}","{'thrust_sea_level': {'kN': 128000, 'lbf': 287...",...,False,2,0,7000000,0,2021-12-01,United States,SpaceX,https://en.wikipedia.org/wiki/SpaceX_Starship,Starship and Super Heavy Rocket represent a fu...

# Step 4: Add Simulated Country Information
● Add a new column country and randomly assign one of these values:
['USA', 'Russia', 'India', 'China', 'France']

In [50]:
import random

# Add random country to each row
merged_df['country'] = [random.choice(['USA', 'Russia', 'India', 'China', 'France']) for _ in range(len(merged_df))]

# Show first few rows
merged_df

,name_x,date_utc,success,details,rocket_id,year,height,diameter,mass,first_stage,...,active,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,wikipedia,description
0,FalconSat,2006-03-24 22:30:00+00:00,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,Russia,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
1,DemoSat,2007-03-21 01:10:00+00:00,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,USA,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
2,Trailblazer,2008-08-03 03:34:00+00:00,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,USA,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
3,RatSat,2008-09-28 23:15:00+00:00,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
4,RazakSat,2009-07-13 03:35:00+00:00,True,None,5e9d0d95eda69955f709d1eb,2009.0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...",...,False,2,0,6700000,40,2006-03-24,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,ArabSat 6A,2019-04-11 22:35:00+00:00,True,SpaceX will launch Arabsat 6A to a geostationa...,5e9d0d95eda69974db09d1ed,2019.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
202,STP-2,2019-06-25 03:30:00+00:00,True,Space Test Program 2 is a rideshare managed by...,5e9d0d95eda69974db09d1ed,2019.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,USA,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
203,USSF-44,2022-11-01 13:41:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,France,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
204,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,None,None,5e9d0d95eda69974db09d1ed,2022.0,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...",...,True,2,2,90000000,100,2018-02-06,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
205,NaN,NaT,NaN,NaN,5e9d0d96eda699382d09d1ee,NaN,"{'meters': 118, 'feet': 387}","{'meters': 9, 'feet': 30}","{'kg': 1335000, 'lb': 2943000}","{'thrust_sea_level': {'kN': 128000, 'lbf': 287...",...,False,2,0,7000000,0,2021-12-01,Russia,SpaceX,https://en.wikipedia.org/wiki/SpaceX_Starship,Starship and Super Heavy Rocket represent a fu...

# Step 5: Store Merged Data in SQLite3
● Use sqlite3 to create a connection and save the merged DataFrame as a table named
launches
● Table should contain all merged columns including country

In [51]:
#since column is dict we have to convert strings so the below code wont work
'''  Connect to SQLite3 database
error

# Save the merged DataFrame to a table named 'launches'
merged_df.to_sql('launches', conn, if_exists='replace', index=False)

# Close the connection
conn.close()''' #since column is dict we have to convert strings so

"  Connect to SQLite3 database\nerror\n\n# Save the merged DataFrame to a table named 'launches'\nmerged_df.to_sql('launches', conn, if_exists='replace', index=False)\n\n# Close the connection\nconn.close()"

In [52]:
# Check datatypes of all columns
print(merged_df.dtypes)

name_x                           object
date_utc            datetime64[ns, UTC]
success                          object
details                          object
rocket_id                        object
year                            float64
height                           object
diameter                         object
mass                             object
first_stage                      object
second_stage                     object
engines                          object
landing_legs                     object
payload_weights                  object
flickr_images                    object
name_y                           object
type                             object
active                             bool
stages                            int64
boosters                          int64
cost_per_launch                   int64
success_rate_pct                  int64
first_flight                     object
country                          object
company                          object
wikipedia                        object
description                      object
dtype: object

In [53]:
# Check which columns contain dicts/lists to convert to strings
for col in merged_df.columns:
    if merged_df[col].apply(lambda x: isinstance(x, (dict, list))).any():
        print(f"⚠️ Column '{col}' contains dict or list values.")

⚠️ Column 'height' contains dict or list values.
⚠️ Column 'diameter' contains dict or list values.
⚠️ Column 'mass' contains dict or list values.
⚠️ Column 'first_stage' contains dict or list values.
⚠️ Column 'second_stage' contains dict or list values.
⚠️ Column 'engines' contains dict or list values.
⚠️ Column 'landing_legs' contains dict or list values.
⚠️ Column 'payload_weights' contains dict or list values.
⚠️ Column 'flickr_images' contains dict or list values.

In [54]:
import pandas as pd
import sqlite3
import json

# Step 1: Convert dict or list columns to string (JSON format)
for col in merged_df.columns:
    if merged_df[col].apply(lambda x: isinstance(x, (dict, list))).any():
        merged_df[col] = merged_df[col].apply(lambda x: json.dumps(x) if isinstance(x, (dict, list)) else x)

In [55]:

# Step 2: Create SQLite connection
conn = sqlite3.connect("spacex_data.db")

# Step 3: Save the converted DataFrame to a table named 'launches'
merged_df.to_sql("launches", conn, if_exists="replace", index=False)


print("✅ Merged data (with complex columns converted) saved to SQLite.")

✅ Merged data (with complex columns converted) saved to SQLite.

In [56]:
pd.read_sql_query("SELECT * FROM launches", conn)

,name_x,date_utc,success,details,rocket_id,year,height,diameter,mass,first_stage,...,active,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,wikipedia,description
0,FalconSat,2006-03-24 22:30:00+00:00,0.0,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,2006.0,"{""meters"": 22.25, ""feet"": 73}","{""meters"": 1.68, ""feet"": 5.5}","{""kg"": 30146, ""lb"": 66460}","{""thrust_sea_level"": {""kN"": 420, ""lbf"": 94000}...",...,0,2,0,6700000,40,2006-03-24,Russia,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
1,DemoSat,2007-03-21 01:10:00+00:00,0.0,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,2007.0,"{""meters"": 22.25, ""feet"": 73}","{""meters"": 1.68, ""feet"": 5.5}","{""kg"": 30146, ""lb"": 66460}","{""thrust_sea_level"": {""kN"": 420, ""lbf"": 94000}...",...,0,2,0,6700000,40,2006-03-24,USA,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
2,Trailblazer,2008-08-03 03:34:00+00:00,0.0,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,2008.0,"{""meters"": 22.25, ""feet"": 73}","{""meters"": 1.68, ""feet"": 5.5}","{""kg"": 30146, ""lb"": 66460}","{""thrust_sea_level"": {""kN"": 420, ""lbf"": 94000}...",...,0,2,0,6700000,40,2006-03-24,USA,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
3,RatSat,2008-09-28 23:15:00+00:00,1.0,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,2008.0,"{""meters"": 22.25, ""feet"": 73}","{""meters"": 1.68, ""feet"": 5.5}","{""kg"": 30146, ""lb"": 66460}","{""thrust_sea_level"": {""kN"": 420, ""lbf"": 94000}...",...,0,2,0,6700000,40,2006-03-24,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
4,RazakSat,2009-07-13 03:35:00+00:00,1.0,None,5e9d0d95eda69955f709d1eb,2009.0,"{""meters"": 22.25, ""feet"": 73}","{""meters"": 1.68, ""feet"": 5.5}","{""kg"": 30146, ""lb"": 66460}","{""thrust_sea_level"": {""kN"": 420, ""lbf"": 94000}...",...,0,2,0,6700000,40,2006-03-24,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,ArabSat 6A,2019-04-11 22:35:00+00:00,1.0,SpaceX will launch Arabsat 6A to a geostationa...,5e9d0d95eda69974db09d1ed,2019.0,"{""meters"": 70, ""feet"": 229.6}","{""meters"": 12.2, ""feet"": 39.9}","{""kg"": 1420788, ""lb"": 3125735}","{""thrust_sea_level"": {""kN"": 22819, ""lbf"": 5130...",...,1,2,2,90000000,100,2018-02-06,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
202,STP-2,2019-06-25 03:30:00+00:00,1.0,Space Test Program 2 is a rideshare managed by...,5e9d0d95eda69974db09d1ed,2019.0,"{""meters"": 70, ""feet"": 229.6}","{""meters"": 12.2, ""feet"": 39.9}","{""kg"": 1420788, ""lb"": 3125735}","{""thrust_sea_level"": {""kN"": 22819, ""lbf"": 5130...",...,1,2,2,90000000,100,2018-02-06,USA,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
203,USSF-44,2022-11-01 13:41:00+00:00,NaN,None,5e9d0d95eda69974db09d1ed,2022.0,"{""meters"": 70, ""feet"": 229.6}","{""meters"": 12.2, ""feet"": 39.9}","{""kg"": 1420788, ""lb"": 3125735}","{""thrust_sea_level"": {""kN"": 22819, ""lbf"": 5130...",...,1,2,2,90000000,100,2018-02-06,France,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
204,Viasat-3 & Arcturus,2022-12-01 00:00:00+00:00,NaN,None,5e9d0d95eda69974db09d1ed,2022.0,"{""meters"": 70, ""feet"": 229.6}","{""meters"": 12.2, ""feet"": 39.9}","{""kg"": 1420788, ""lb"": 3125735}","{""thrust_sea_level"": {""kN"": 22819, ""lbf"": 5130...",...,1,2,2,90000000,100,2018-02-06,India,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...
205,None,None,NaN,None,5e9d0d96eda699382d09d1ee,NaN,"{""meters"": 118, ""feet"": 387}","{""meters"": 9, ""feet"": 30}","{""kg"": 1335000, ""lb"": 2943000}","{""thrust_sea_level"": {""kN"": 128000, ""lbf"": 287...",...,0,2,0,7000000,0,2021-12-01,Russia,SpaceX,https://en.wikipedia.org/wiki/SpaceX_Starship,Starship and Super Heavy Rocket represent a fu...

In [57]:
# when we Check which columns contain dicts/lists again, nothing is displayed. Hence no more columns in dict/list
for col in merged_df.columns:
    if merged_df[col].apply(lambda x: isinstance(x, (dict, list))).any():
        print(f"⚠️ Column '{col}' contains dict or list values.")

# Step 6: Run SQL Queries on the Data to analyze
1. Launches by Country
2. Which year had the highest number of launches?
3. Top 5 Missions by Launch Count

In [58]:
# prompt: Step 6: Run SQL Queries on the Data to analyze
# 1. Launches by Country
# 2. Which year had the highest number of launches?


query1 = """
SELECT country, COUNT(*) AS launch_count
FROM launches
GROUP BY country
ORDER BY launch_count DESC;
"""
pd.read_sql(query1, conn)

  country  launch_count
0  Russia            48
1   China            44
2   India            39
3     USA            38
4  France            37

In [59]:
# 2. Which year had the highest number of launches?
query2 = """
SELECT year, COUNT(*) AS launch_count
FROM launches
GROUP BY year
ORDER BY launch_count DESC
LIMIT 1;
"""
pd.read_sql(query2, conn)

     year  launch_count
0  2022.0            62

In [60]:
# 3. Top 5 Missions by Launch Count
query3 = """
SELECT name_x AS mission_name, COUNT(*) AS times_launched
FROM launches
GROUP BY mission_name
ORDER BY times_launched DESC
LIMIT 5;
"""
pd.read_sql(query3, conn)

                mission_name  times_launched
0  ispace Mission 1 & Rashid               1
1                       ZUMA               1
2     WorldView Legion 1 & 2               1
3        Viasat-3 & Arcturus               1
4                    USSF-44               1